### ISSUE TITLE
Why adds are removed

### ISSUE THREAD

**Issue by franpog859** [jumpalottahigh/blog.georgi-yanev.com#26]
Why did you decide to remove the ads which use `react-adsense`? I'm trying to find some good references of its usage and I see many repos decided to get rid of them

**Comment by jumpalottahigh** [comment]
@franpog859 I had no issues with the module itself, it worked like a charm. For me the whole thing was just a test anyway to see if it would make sense for me to run ads or not. For a few bucks per month to slow down and ruin the experience of my users by making them download extra JavaScript and display ads, just didn't make sense for me.

**Comment by franpog859** [comment]
Thanks a lot for the information!

**Comment by jumpalottahigh** [comment]
Sure, happy to help :)
